[backends]
[backends.backend1]
    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://localhost:8080"

[frontends]


[frontends.frontend1]
  entryPoints = ["http", "https"]
  backend = "backend1"
  passHostHeader = true[frontends.frontend1.routes]
    [frontends.frontend1.routes.route0]
      rule = "Host:mydomain.com"
